# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# Don't edit manually! Use `build.bat version` command instead!
version: 1.6.30-build-0{build}

os: Visual Studio 2015

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  BuildEnvironment: appveyor
  Hangfire_SqlServer_ConnectionStringTemplate: Server=.\SQL2008R2SP2;Database={0};User Id=sa;Password=Password12!

# enable service required for tests
services:
  - mssql2008r2sp2
  - msmq

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true

cache:
  - packages

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  - build.bat ci

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: 8BQmcR1hP9MoxvrmXJKMtlRyX6LI36H9ZTU8fSEetvzMGCl1PUlXKZRUGq+GVMja
    on:
      appveyor_repo_tag: true
